-- Seed tours data
INSERT INTO tours (id, title, slug, location, duration, difficulty, price, original_price, rating, review_count, image, gallery, short_description, description, highlights, inclusions, exclusions, itinerary, next_date, registration_deadline, spots_left, max_group_size, views, inquiries, featured, category)
VALUES
    (gen_random_uuid(), 'Mount Kenya Summit Expedition', 'mount-kenya-summit', 'Mount Kenya, Kenya', '5 Days', 'Challenging', 1299, 1499, 4.9, 127, 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800&q=80', '{}', 'Conquer Africa''s second-highest peak through pristine alpine wilderness.', 'Experience the ultimate East African adventure as you summit Point Lenana on Mount Kenya. This expedition takes you through diverse ecosystems, from bamboo forests to alpine moorlands.', ARRAY['Summit Point Lenana at 4,985m', 'Traverse unique Afro-alpine landscapes', 'Spot rare wildlife including rock hyrax', 'Professional mountain guides', 'Sunrise views over the African plains'], ARRAY['Professional mountain guide', 'All park fees and permits', 'Quality camping equipment', 'All meals during the trek', 'Airport transfers', 'First aid kit and oxygen'], ARRAY['International flights', 'Travel insurance', 'Personal gear', 'Tips and gratuities', 'Alcoholic beverages'], '[{"day": 1, "title": "Arrival & Briefing", "description": "Arrive at Nairobi, transfer to Nanyuki for overnight and expedition briefing."}, {"day": 2, "title": "Sirimon Gate to Old Moses", "description": "Begin trek through montane forest. Altitude: 3,300m."}, {"day": 3, "title": "Old Moses to Shipton''s Camp", "description": "Trek across moorland to Shipton''s Camp. Altitude: 4,200m."}, {"day": 4, "title": "Summit Day", "description": "Early morning summit push to Point Lenana, descend to Mackinder''s Camp."}, {"day": 5, "title": "Descent & Departure", "description": "Final descent and transfer back to Nairobi."}]'::jsonb '2026-03-15', '2026-03-10', 6, 12, 2847, 89, true, 'Mountain Expeditions'),
    
    (gen_random_uuid(), 'Maasai Mara Walking Safari', 'maasai-mara-walking', 'Maasai Mara, Kenya', '4 Days', 'Moderate', 899, NULL, 4.8, 203, 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', '{}', 'Walk alongside the Great Migration with Maasai warriors as your guides.', 'An intimate walking safari experience in the world-famous Maasai Mara. Walk with experienced Maasai guides through the savannah, tracking wildlife on foot.', ARRAY['Walk with Maasai warrior guides', 'Close encounters with wildlife', 'Witness the Great Migration (seasonal)', 'Traditional Maasai village visit', 'Luxury tented camp experience'], ARRAY['Maasai guide and armed ranger', 'Luxury tented accommodation', 'All meals and beverages', 'Game drives', 'Cultural visits', 'Park fees'], ARRAY['Flights to Maasai Mara', 'Travel insurance', 'Personal items', 'Tips'], '[{"day": 1, "title": "Arrival at Mara", "description": "Fly into Mara, afternoon game drive to camp."}, {"day": 2, "title": "Walking Safari", "description": "Full day walking safari with Maasai guides."}, {"day": 3, "title": "Migration Tracking", "description": "Early morning walk, afternoon game drive."}, {"day": 4, "title": "Departure", "description": "Morning walk, fly back to Nairobi."}]'::jsonb, '2026-02-28', '2026-02-23', 4, 8, 3421, 156, true, 'Safari Adventures'),
    
    (gen_random_uuid(), 'Hell''s Gate Cycling Adventure', 'hells-gate-cycling', 'Naivasha, Kenya', '1 Day', 'Easy', 89, NULL, 4.7, 312, 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', '{}', 'Cycle through dramatic gorges and spot wildlife in Kenya''s unique park.', 'Experience Hell''s Gate National Park on two wheels. Cycle past towering cliffs, through narrow gorges, and alongside zebras and giraffes.', ARRAY['Cycle alongside wildlife', 'Explore dramatic gorges', 'Natural hot springs', 'Rock climbing options', 'Stunning photography spots'], ARRAY['Mountain bike rental', 'Helmet and gear', 'Park entry fees', 'Professional guide', 'Packed lunch', 'Transport from Nairobi'], ARRAY['Personal items', 'Tips', 'Travel insurance'], '[{"day": 1, "title": "Full Day Adventure", "description": "Early departure from Nairobi, full day cycling and gorge exploration, return by evening."}]'::jsonb, '2026-02-10', '2026-02-07', 15, 20, 5632, 234, true, 'Day Trips'),
    
    (gen_random_uuid(), 'Kilimanjaro Lemosho Route', 'kilimanjaro-lemosho', 'Mount Kilimanjaro, Tanzania', '8 Days', 'Extreme', 2899, 3299, 5.0, 78, 'https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=800&q=80', '{}', 'The most scenic route to Africa''s highest peak with highest success rate.', 'Take on the Roof of Africa via the stunning Lemosho Route. Known for its scenic beauty and high success rate, this route offers the ultimate Kilimanjaro experience.', ARRAY['Summit Uhuru Peak at 5,895m', 'Highest summit success rate', 'Diverse ecological zones', 'Stunning Shira Plateau views', 'Smaller crowds'], ARRAY['KPAP certified guides', 'All park fees', 'Quality camping gear', 'All meals on mountain', 'Rescue fees', 'Certificate'], ARRAY['Flights', 'Visa fees', 'Travel insurance', 'Personal gear', 'Tips'], '[{"day": 1, "title": "Londorossi Gate to Mti Mkubwa", "description": "Drive to gate, trek through rainforest."}, {"day": 2, "title": "Shira 1 Camp", "description": "Ascend to Shira Plateau."}, {"day": 3, "title": "Shira 2 Camp", "description": "Acclimatization day with optional hike."}, {"day": 4, "title": "Barranco Camp", "description": "Trek via Lava Tower for acclimatization."}, {"day": 5, "title": "Karanga Camp", "description": "Scale Barranco Wall, short trek."}, {"day": 6, "title": "Barafu Camp", "description": "Rest day, prepare for summit."}, {"day": 7, "title": "Summit Day", "description": "Midnight start, summit Uhuru Peak."}, {"day": 8, "title": "Mweka Gate", "description": "Final descent and celebration."}]'::jsonb, '2026-04-01', '2026-03-25', 3, 10, 1892, 67, false, 'Mountain Expeditions'),
    
    (gen_random_uuid(), 'Aberdare Waterfall Trail', 'aberdare-waterfall', 'Aberdare National Park, Kenya', '2 Days', 'Moderate', 349, NULL, 4.6, 89, 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80', '{}', 'Chase waterfalls through misty mountain forests.', 'Discover the hidden waterfalls of Aberdare National Park. Trek through bamboo forests and moorlands to find spectacular cascades.', ARRAY['Visit 5 stunning waterfalls', 'Bamboo forest trekking', 'Chance to spot bongo antelope', 'Overnight at historic Treetops Lodge', 'Night game viewing'], ARRAY['Park fees', 'Accommodation', 'All meals', 'Guide fees', 'Transport'], ARRAY['Personal items', 'Tips', 'Alcoholic drinks'], '[{"day": 1, "title": "Forest Trek", "description": "Trek to Karuru Falls and Chania Falls, overnight at Treetops."}, {"day": 2, "title": "Moorland Exploration", "description": "Morning trek to Gura Falls, afternoon return."}]'::jsonb, '2026-02-17', '2026-02-14', 8, 12, 1456, 45, false, 'Hiking Trails'),
    
    (gen_random_uuid(), 'Lake Turkana Expedition', 'lake-turkana-expedition', 'Northern Kenya', '7 Days', 'Challenging', 1899, NULL, 4.9, 34, 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80', '{}', 'Journey to the Jade Sea through Kenya''s remote frontier.', 'An epic expedition to Lake Turkana, the world''s largest desert lake. Experience incredible landscapes, tribal cultures, and otherworldly scenery.', ARRAY['Visit the Jade Sea', 'Meet Turkana and El Molo tribes', 'Explore volcanic landscapes', 'Sleep under desert stars', 'Off-the-beaten-path adventure'], ARRAY['4x4 vehicle with driver', 'Camping equipment', 'All meals', 'Guide', 'Community fees'], ARRAY['Flights', 'Travel insurance', 'Personal items', 'Tips'], '[{"day": 1, "title": "Nairobi to Samburu", "description": "Drive north through changing landscapes."}, {"day": 2, "title": "Samburu to Marsabit", "description": "Cross the Chalbi Desert."}, {"day": 3, "title": "Marsabit Exploration", "description": "Explore crater lakes and forests."}, {"day": 4, "title": "To Loiyangalani", "description": "Descend to Lake Turkana."}, {"day": 5, "title": "Lake Turkana", "description": "Full day at the Jade Sea."}, {"day": 6, "title": "South Island", "description": "Boat trip to South Island."}, {"day": 7, "title": "Return Journey", "description": "Fly back to Nairobi."}]'::jsonb, '2026-05-10', '2026-05-03', 5, 8, 2134, 78, true, 'Expedition');

-- Note: The actual tour IDs will be auto-generated as UUIDs. 
-- You'll need to fetch the actual IDs from the tours table to insert bookings correctly.
-- For now, bookings will be inserted manually or through the application.
